'use client';

import { useParams, useRouter } from 'next/navigation';
import { Navbar } from '@/components/layout/navbar';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select } from '@/components/ui/select';
import { SECTIONS, SECTION_IDS, SectionId } from '@/lib/constants';
import { Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';

// Cheat sheet content for each section
const CHEATSHEETS: Record<SectionId, { title: string; content: string[]; examples?: string[] }> = {
  calcul_mental: {
    title: 'Calcul Mental',
    content: [
      '🎯 OBJECTIF: Calculer rapidement et sans erreur (15 questions en 20 min)',
      '',
      'MULTIPLICATION RAPIDE',
      '• Par 11: Additionner les chiffres adjacents (ex: 23×11 = 2|(2+3)|3 = 253)',
      '  → Si somme > 9, reporter la retenue (ex: 48×11 = 4|(4+8)|8 = 528)',
      '• Par 5: Diviser par 2 puis multiplier par 10 (ou ajouter 0 et ÷2)',
      '  → Exemple: 24×5 = 24÷2×10 = 120',
      '• Par 15: Multiplier par 10 puis ajouter la moitié (n×15 = n×10 + n×5)',
      '  → Exemple: 24×15 = 240 + 120 = 360',
      '• Par 25: Diviser par 4 puis multiplier par 100',
      '  → Exemple: 28×25 = 28÷4×100 = 700',
      '• Par 9: Multiplier par 10 puis soustraire (n×9 = n×10 - n)',
      '  → Exemple: 13×9 = 130 - 13 = 117',
      '• Carrés: (a+b)² = a² + 2ab + b² | (a-b)² = a² - 2ab + b²',
      '  → Exemple: 23² = (20+3)² = 400 + 120 + 9 = 529',
      '',
      'DIVISION RAPIDE',
      '• Diviser par 4: Diviser par 2 deux fois (÷4 = ÷2÷2)',
      '  → Exemple: 84÷4 = 84÷2÷2 = 42÷2 = 21',
      '• Diviser par 8: Diviser par 2 trois fois (÷8 = ÷2÷2÷2)',
      '  → Exemple: 64÷8 = 64÷2÷2÷2 = 8',
      '• Diviser par 5: Multiplier par 2 puis diviser par 10',
      '  → Exemple: 125÷5 = 125×2÷10 = 250÷10 = 25',
      '',
      'POURCENTAGES - À MÉMORISER PAR CŒUR',
      '• 10% = ÷10 (déplacer virgule 1 rang gauche)',
      '• 20% = ÷5 (ou 10% × 2)',
      '• 25% = ÷4 (ou 50% ÷ 2)',
      '• 33% ≈ ÷3 (ou 1/3)',
      '• 50% = ÷2',
      '• 75% = ×3÷4 (ou 50% + 25%)',
      '• Augmentation de x%: multiplier par (1 + x/100)',
      '  → Exemple: 100€ + 20% = 100 × 1.20 = 120€',
      '• Diminution de x%: multiplier par (1 - x/100)',
      '  → Exemple: 100€ - 15% = 100 × 0.85 = 85€',
      '• PIÈGE: 100€ + 20% puis -20% ≠ 100€ (120€ - 20% = 96€)',
      '',
      'FRACTIONS COURANTES',
      '• 1/2 = 50% | 1/3 ≈ 33% | 1/4 = 25% | 1/5 = 20%',
      '• 2/3 ≈ 67% | 3/4 = 75% | 1/10 = 10%',
      '',
      'ADDITION/SOUSTRACTION RAPIDE',
      '• Arrondir puis ajuster: 48+37 = (48+2)+(37-2) = 50+35 = 85',
      '• Utiliser les compléments à 10: 7+8 = 7+3+5 = 10+5 = 15',
      '• Soustraire: 73-28 = 73-30+2 = 45',
      '',
      'TABLEAUX DE CALCUL MENTAL - MÉTHODE SYSTÉMATIQUE',
      'Pour les calculs complexes, utiliser un tableau:',
      '',
      'Exemple: Calculer 47 × 23',
      '  Méthode: 47 × 23 = 47 × (20 + 3) = 47×20 + 47×3',
      '  Tableau:',
      '  Calcul     |  Résultat',
      '  47 × 20    |   940',
      '  47 × 3     |   141',
      '  Total      |   1081',
      '',
      'Exemple: Calculer 15% de 240',
      '  Méthode: Décomposer en pourcentages connus',
      '  Tableau:',
      '  Pourcentage  |  Calcul    |  Résultat',
      '     10%       |  240 ÷ 10  |    24',
      '      5%       |  24 ÷ 2    |    12',
      '     15%       |  24 + 12   |    36',
      '',
      'RACINES CARRÉES - ESTIMATION',
      '• √50 ≈ 7 (car 7²=49) | √80 ≈ 9 (car 9²=81)',
      '• Utiliser les carrés connus: 1² à 20²',
      '',
      'ASTUCES GAGNANTES',
      '• Vérifier la parité du résultat (pair/impair)',
      '• Vérifier l\'ordre de grandeur (100, 1000, etc.)',
      '• Utiliser les propriétés commutatives et associatives',
      '• Factoriser quand possible',
      '• Éliminer les zéros en fin de calcul',
      '',
      'ASTUCES GAGNANTES POUR AVOIR DE BONNES NOTES',
      '• Mémorisez les carrés jusqu\'à 20² et cubes jusqu\'à 10³ (flashcards)',
      '• Connaissez les critères de divisibilité par cœur (1 à 15)',
      '• Apprenez les fractions courantes: 1/2, 1/3, 1/4, 1/5, 2/3, 3/4',
      '• Vérifiez toujours la parité du résultat (pair/impair)',
      '• Vérifiez l\'ordre de grandeur (100, 1000, etc.)',
      '• Éliminez les zéros en fin de calcul pour simplifier',
      '• Utilisez les arrondis pour vérifier rapidement',
      '• En cas de doute, testez avec des nombres simples',
      '',
      'EXEMPLES DE TEST - QUESTIONS TYPES',
      'Q1: 47 × 11 = ?',
      '  → 4|(4+7)|7 = 4|11|7 = 517 (retenue: 4+1=5)',
      '  → Réponse: 517',
      '',
      'Q2: 15% de 240 = ?',
      '  → 10% = 24, 5% = 12, donc 15% = 24 + 12 = 36',
      '  → Réponse: 36',
      '',
      'Q3: 84 ÷ 4 = ?',
      '  → 84÷2 = 42, 42÷2 = 21',
      '  → Réponse: 21',
      '',
      'Q4: Un prix passe de 80€ à 100€. Quelle est l\'augmentation en % ?',
      '  → ((100-80)/80) × 100 = (20/80) × 100 = 0.25 × 100 = 25%',
      '  → Réponse: 25%',
      '',
      'Q5: 37 × 25 = ?',
      '  → 37÷4 = 9.25, donc 9.25×100 = 925',
      '  → Ou: 37×100 = 3700, 3700÷4 = 925',
      '  → Réponse: 925',
      '',
      'Q6: 156 ÷ 8 = ?',
      '  → 156÷2 = 78, 78÷2 = 39, 39÷2 = 19.5',
      '  → Réponse: 19.5',
      '',
      'Q7: 28% de 150 = ?',
      '  → 25% = 37.5, 3% = 4.5, donc 28% = 37.5 + 4.5 = 42',
      '  → Réponse: 42',
      '',
      'Q8: √72 ≈ ?',
      '  → √64 = 8, √81 = 9, donc √72 ≈ 8.5',
      '  → Réponse: environ 8.5',
    ],
    examples: [
      'Exemple 1: Calculer 37 × 15',
      '→ 37×10 = 370, 37×5 = 185, donc 370+185 = 555',
      '',
      'Exemple 2: 28% de 250',
      '→ 25% = 62.5, 3% = 7.5, donc 28% = 70',
      '',
      'Exemple 3: 156 ÷ 4',
      '→ 156÷2 = 78, 78÷2 = 39',
    ],
  },
  raisonnement_logique: {
    title: 'Raisonnement Logique',
    content: [
      '🎯 OBJECTIF: Analyser des raisonnements et déduire des conclusions (15 questions en 20 min)',
      '',
      'LOGIQUE PROPOSITIONNELLE - FONDAMENTAL',
      '• Si P alors Q (P → Q): Faux SEULEMENT si P vrai ET Q faux',
      '  → Table de vérité: V→V=V, V→F=F, F→V=V, F→F=V',
      '• Contraposée: Si P→Q alors non-Q→non-P (équivalent)',
      '  → Exemple: "S\'il pleut alors sol mouillé" = "Si sol sec alors il ne pleut pas"',
      '• ERREUR CLASSIQUE: Si P→Q et Q vrai, on NE PEUT PAS conclure P (affirmation du conséquent)',
      '  → Exemple: "Si il pleut alors sol mouillé" + "sol mouillé" ≠ "il pleut"',
      '• P si et seulement si Q (P ↔ Q): Vrai si P et Q ont même valeur (équivalence)',
      '',
      'TABLEAUX DE VÉRITÉ - MÉTHODE SYSTÉMATIQUE',
      'Tableau pour P → Q (Si P alors Q):',
      '  P  |  Q  |  P→Q',
      '  V  |  V  |   V',
      '  V  |  F  |   F  ← SEUL CAS FAUX',
      '  F  |  V  |   V',
      '  F  |  F  |   V',
      '',
      'Tableau pour P ↔ Q (P si et seulement si Q):',
      '  P  |  Q  |  P↔Q',
      '  V  |  V  |   V',
      '  V  |  F  |   F',
      '  F  |  V  |   F',
      '  F  |  F  |   V',
      '',
      'Tableau pour P ET Q:',
      '  P  |  Q  |  P∧Q',
      '  V  |  V  |   V',
      '  V  |  F  |   F',
      '  F  |  V  |   F',
      '  F  |  F  |   F',
      '',
      'Tableau pour P OU Q:',
      '  P  |  Q  |  P∨Q',
      '  V  |  V  |   V',
      '  V  |  F  |   V',
      '  F  |  V  |   V',
      '  F  |  F  |   F  ← SEUL CAS FAUX',
      '',
      'NÉGATION - LOIS DE DE MORGAN',
      '• Négation de "tous": "au moins un ne"',
      '  → non(∀x P(x)) = ∃x non-P(x)',
      '• Négation de "aucun": "au moins un"',
      '  → non(∀x non-P(x)) = ∃x P(x)',
      '• Négation de "A ET B": "non-A OU non-B"',
      '  → Exemple: "pas (riche ET célèbre)" = "pauvre OU inconnu"',
      '• Négation de "A OU B": "non-A ET non-B"',
      '  → Exemple: "pas (riche OU célèbre)" = "pauvre ET inconnu"',
      '',
      'QUANTIFICATEURS - DIFFÉRENCES CRUCIALES',
      '• "Tous" = 100% (tous les X sont Y)',
      '• "Quelques" = au moins un (peut être tous)',
      '• "Aucun" = 0% (aucun X n\'est Y)',
      '• "Certains" = au moins un (comme "quelques")',
      '',
      'SYLLOGISMES - TRANSITIVITÉ',
      '• Tous les A sont B, tous les B sont C → Tous les A sont C ✓',
      '  → Exemple: "Tous chats sont animaux" + "Tous animaux respirent" → "Tous chats respirent"',
      '• Aucun A n\'est B, tous les B sont C → Aucun A n\'est C ✓',
      '• Tous les A sont B, quelques B sont C → Rien ne peut être conclu ✗',
      '',
      'DIAGRAMMES DE VENN - MÉTHODE VISUELLE',
      '• Dessiner des cercles qui se chevauchent',
      '• Zone d\'intersection = éléments communs aux deux ensembles',
      '• Zone extérieure = éléments n\'appartenant à aucun ensemble',
      '• Exemple: A = étudiants, B = sportifs',
      '  → Intersection = étudiants sportifs',
      '  → Zone A seule = étudiants non-sportifs',
      '  → Zone B seule = sportifs non-étudiants',
      '',
      'TABLEAUX À DOUBLE ENTRÉE - MÉTHODE SYSTÉMATIQUE',
      'Pour analyser les relations entre plusieurs propositions:',
      '',
      'Exemple: "Tous les A sont B. Quelques B sont C."',
      '  Tableau:',
      '        |  C   |  non-C',
      '  A     |  ?   |   ?',
      '  non-A |  ?   |   ?',
      '',
      'Méthode:',
      '1. Remplir ce qui est certain (tous A sont B)',
      '2. Déduire ce qui est impossible',
      '3. Identifier ce qui est possible mais non certain',
      '',
      'TABLEAUX DE DÉDUCTION - MÉTHODE EN 3 ÉTAPES',
      'Étape 1: Lister toutes les informations',
      'Étape 2: Créer un tableau avec toutes les possibilités',
      'Étape 3: Éliminer les impossibilités',
      '',
      'Exemple: "X est nécessaire pour Y. Y est suffisant pour Z."',
      '  Tableau:',
      '  X  |  Y  |  Z  |  Possible ?',
      '  V  |  V  |  V  |   OUI',
      '  V  |  V  |  F  |   NON (Y suffit pour Z)',
      '  V  |  F  |  V  |   NON (X nécessaire pour Y)',
      '  V  |  F  |  F  |   OUI',
      '  F  |  V  |  V  |   NON (X nécessaire pour Y)',
      '  F  |  V  |  F  |   NON (X nécessaire pour Y)',
      '  F  |  F  |  V  |   NON (X nécessaire pour Y)',
      '  F  |  F  |  F  |   OUI',
      '',
      'CONDITIONS NÉCESSAIRES VS SUFFISANTES',
      '• Nécessaire: Sans elle, impossible (mais ne garantit pas)',
      '  → Exemple: "Avoir 18 ans" est nécessaire pour voter',
      '• Suffisante: Avec elle, garanti (mais pas la seule)',
      '  → Exemple: "Être président" est suffisant pour avoir le pouvoir',
      '• Nécessaire ET suffisante: Équivalence (si et seulement si)',
      '',
      'PREUVE PAR L\'ABSURDE',
      '• Si on arrive à "A ET non-A", alors l\'hypothèse initiale est fausse',
      '',
      'PIÈGES FRÉQUENTS',
      '• Ne pas confondre "si" et "seulement si"',
      '• "Seulement si" = condition nécessaire (A seulement si B = si A alors B)',
      '• Attention aux quantificateurs (tous, certains, aucun)',
      '• Vérifier la réciproque d\'une implication',
      '• Ne pas inverser les quantificateurs',
      '',
      'ASTUCES GAGNANTES POUR AVOIR DE BONNES NOTES',
      '• Dessinez des diagrammes de Venn pour visualiser',
      '• Testez avec des exemples concrets si vous êtes bloqué',
      '• Attention aux mots "tous", "aucun", "quelques" - ils changent tout !',
      '• La contraposée est votre amie: P→Q = non-Q→non-P',
      '• Ne confondez JAMAIS "si" et "seulement si"',
      '• Vérifiez toujours la réciproque d\'une implication',
      '• Utilisez des tableaux de vérité pour les cas complexes',
      '',
      'EXEMPLES DE TEST - QUESTIONS TYPES',
      'Q1: "Tous les étudiants sont travailleurs. Quelques travailleurs sont sportifs."',
      '  → Peut-on conclure que quelques étudiants sont sportifs ?',
      '  → NON (les sportifs peuvent être d\'autres travailleurs)',
      '  → Réponse: Non, on ne peut pas conclure',
      '',
      'Q2: Si "A→B" est vrai et B est faux, que peut-on dire de A ?',
      '  → Contraposée: non-B→non-A, donc si B faux alors A faux',
      '  → Réponse: A est faux',
      '',
      'Q3: La négation de "Tous les X sont Y" est ?',
      '  → "Au moins un X n\'est pas Y"',
      '  → Réponse: "Au moins un X n\'est pas Y"',
      '',
      'Q4: "Tous les chats sont des animaux. Tous les animaux respirent."',
      '  → Que peut-on conclure ?',
      '  → Transitivité: Tous les chats respirent ✓',
      '  → Réponse: Tous les chats respirent',
      '',
      'Q5: "Si il pleut alors le sol est mouillé. Le sol est mouillé."',
      '  → Peut-on conclure qu\'il pleut ?',
      '  → NON (erreur classique: affirmation du conséquent)',
      '  → Le sol peut être mouillé pour d\'autres raisons',
      '  → Réponse: Non, on ne peut pas conclure',
      '',
      'Q6: Négation de "Tous les étudiants sont présents ET tous sont à l\'heure"',
      '  → Loi de De Morgan: "Au moins un étudiant n\'est pas présent OU au moins un n\'est pas à l\'heure"',
      '  → Réponse: "Au moins un étudiant n\'est pas présent OU au moins un n\'est pas à l\'heure"',
    ],
    examples: [
      'Exemple 1: "Tous les médecins sont diplômés. Tous les diplômés ont étudié."',
      '→ Conclusion: Tous les médecins ont étudié ✓',
      '',
      'Exemple 2: "Si il fait beau alors je vais à la plage. Je vais à la plage."',
      '→ Peut-on conclure qu\'il fait beau ? NON (erreur classique)',
      '',
      'Exemple 3: Négation de "Tous les chats sont noirs"',
      '→ "Au moins un chat n\'est pas noir"',
    ],
  },
  expression: {
    title: 'Expression',
    content: [
      '🎯 OBJECTIF: Maîtriser la grammaire et l\'orthographe (15 questions en 20 min)',
      '',
      'ORTHOGRAPHE - CONFUSIONS FRÉQUENTES',
      '• a/à: "a" = verbe avoir (3e pers.) | "à" = préposition',
      '  → Test: Remplacer par "avait" → "Il a faim" = "Il avait faim" ✓',
      '  → "Il va à Paris" → "Il va avait Paris" ✗ donc "à"',
      '• ou/où: "ou" = conjonction (ou bien) | "où" = pronom/adverbe de lieu',
      '  → Test: Remplacer par "ou bien" → "Tu veux du thé ou du café ?" ✓',
      '  → "Où vas-tu ?" → "Ou bien vas-tu ?" ✗ donc "où"',
      '• ce/se: "ce" = déterminant démonstratif | "se" = pronom réfléchi',
      '  → "Ce livre" (déterminant) | "Il se lave" (pronom)',
      '• ces/ses: "ces" = démonstratif | "ses" = possessif',
      '  → Test: "Ces livres" = ces livres-là | "Ses livres" = les livres à lui',
      '  → Test possessif: Remplacer par "les siens" → "Ses livres" = "les siens" ✓',
      '',
      'ACCORD DU PARTICIPE PASSÉ - RÈGLES ESSENTIELLES',
      '• Avec "être": TOUJOURS accordé avec le sujet',
      '  → "Elle est partie" (accord avec "elle")',
      '  → "Ils sont arrivés" (accord avec "ils")',
      '• Avec "avoir": Accordé avec le COD SEULEMENT si placé AVANT le verbe',
      '  → "J\'ai cueilli des fleurs" (COD "fleurs" après → invariable)',
      '  → "Les fleurs que j\'ai cueillies" (COD "que" avant → accordé)',
      '  → Test: Poser la question "J\'ai cueilli quoi ?" → "des fleurs" (après) = invariable',
      '',
      'SUBJONCTIF - QUAND L\'UTILISER',
      '• Après "il faut que", "bien que", "pour que", "avant que"',
      '  → "Il faut que tu viennes" (subjonctif)',
      '  → "Bien qu\'il pleuve" (subjonctif)',
      '• Après expressions de doute/volonté: "je doute que", "je veux que"',
      '  → "Je doute qu\'il vienne" (subjonctif)',
      '• Après "il est important que", "il est nécessaire que"',
      '',
      'ACCORDS COMPLEXES',
      '• "La plupart" + nom: Accord avec le complément',
      '  → "La plupart des gens sont" (accord avec "gens")',
      '  → "La plupart du temps est" (accord avec "temps")',
      '• "Une foule de", "une majorité de": Accord avec le complément',
      '  → "Une foule de gens sont" (accord avec "gens")',
      '• "Tout": Invariable sauf devant nom féminin singulier',
      '  → "Tout le monde" (masculin, invariable)',
      '  → "Toute la journée" (féminin, accordé)',
      '  → "Tous les jours" (pluriel, accordé)',
      '• "Même": Adjectif (accordé) ou adverbe (invariable)',
      '  → "Les mêmes personnes" (adjectif, accordé)',
      '  → "Même les enfants" (adverbe, invariable)',
      '  → Test: Peut-on le supprimer ? Si oui = adverbe',
      '• "Demi": Invariable avant le nom, accordé après',
      '  → "Une demi-heure" (avant, invariable)',
      '  → "Une heure et demie" (après, accordé)',
      '• "Quelque": Invariable devant nombre, pluriel devant nom',
      '  → "Quelque 200 personnes" (devant nombre, invariable)',
      '  → "Quelques personnes" (devant nom, pluriel)',
      '',
      'SYNTAXE',
      '• Éviter les répétitions (utiliser des synonymes)',
      '• Respecter la concordance des temps',
      '• Placer correctement les pronoms compléments',
      '• Éviter les constructions lourdes',
      '',
      'TABLEAUX D\'ACCORD - MÉTHODE SYSTÉMATIQUE',
      'Pour déterminer les accords complexes:',
      '',
      'Tableau d\'accord du participe passé avec "avoir":',
      '  COD placé  |  Exemple                    |  Accord',
      '  Avant      |  "Les fleurs que j\'ai cueillies" |  OUI',
      '  Après      |  "J\'ai cueilli des fleurs"      |  NON',
      '',
      'Tableau d\'accord avec collectifs:',
      '  Expression        |  Accord avec        |  Exemple',
      '  "La plupart de"   |  Complément        |  "La plupart des gens sont"',
      '  "Une foule de"    |  Complément        |  "Une foule de gens sont"',
      '  "Avec"            |  Sujet             |  "L\'équipe avec supporters est"',
      '',
      'Tableau des tests orthographiques:',
      '  Mot    |  Test                    |  Si marche =  |  Sinon =',
      '  a/à    |  Remplacer par "avait"   |  "a" (verbe)  |  "à" (préposition)',
      '  ou/où  |  Remplacer par "ou bien" |  "ou" (conj.) |  "où" (lieu)',
      '  ces/ses|  Remplacer par "les siens"| "ses" (poss.)|  "ces" (dém.)',
      '',
      'VOCABULAIRE - PARONYMES FRÉQUENTS',
      '• affecter/effacer: "affecter" = toucher/influencer | "effacer" = supprimer',
      '• amener/emmener: "amener" = vers soi | "emmener" = avec soi',
      '• différer/transférer: "différer" = reporter | "transférer" = déplacer',
      '• éminent/imminent: "éminent" = remarquable | "imminent" = proche',
      '',
      'PIÈGES CLASSIQUES',
      '• "Avec" + nom: Accord généralement avec le sujet (pas le complément)',
      '  → "L\'équipe avec ses supporters est venue" (accord avec "équipe")',
      '  → Exception: Si "avec" = "et", accord au pluriel',
      '• Ne pas confondre "davantage" (adverbe) et "d\'avantage" (nom)',
      '',
      'ASTUCES GAGNANTES POUR AVOIR DE BONNES NOTES',
      '• Testez "a/à" en remplaçant par "avait"',
      '• Testez "ou/où" en remplaçant par "ou bien"',
      '• Testez "ces/ses" en remplaçant par "les siens"',
      '• Pour participe passé avec "avoir": posez "J\'ai fait QUOI ?"',
      '• Mémorisez les expressions qui demandent le subjonctif',
      '• Attention aux accords avec "la plupart", "une foule de"',
      '• Vérifiez toujours l\'accord de "tout" (invariable sauf féminin singulier)',
      '',
      'EXEMPLES DE TEST - QUESTIONS TYPES',
      'Q1: "Les fleurs que j\'ai (cueilli/cueillies)"',
      '  → COD "que" = fleurs, placé AVANT → accordé',
      '  → Réponse: cueillies',
      '',
      'Q2: "Il (a/à) mangé"',
      '  → Test: "Il avait mangé" ✓ donc "a" (verbe avoir)',
      '  → Réponse: a',
      '',
      'Q3: "Il va (a/à) Paris"',
      '  → Test: "Il va avait Paris" ✗ donc "à" (préposition)',
      '  → Réponse: à',
      '',
      'Q4: "Tous les étudiants (est/sont) présents"',
      '  → Sujet "étudiants" (pluriel) → verbe au pluriel',
      '  → Réponse: sont',
      '',
      'Q5: "La plupart des gens (est/sont)"',
      '  → Accord avec "gens" (complément) → pluriel',
      '  → Réponse: sont',
      '',
      'Q6: "Bien qu\'il (pleuve/pleut)"',
      '  → Après "bien que" → subjonctif',
      '  → Réponse: pleuve',
      '',
      'Q7: "Les pommes que j\'ai (acheté/achetées)"',
      '  → COD "que" = pommes (féminin pluriel), avant le verbe → accordé',
      '  → Réponse: achetées',
      '',
      'Q8: "(Tout/Tous) le monde est présent"',
      '  → "Monde" est masculin singulier → "tout" invariable',
      '  → Réponse: Tout',
    ],
    examples: [
      'Exemple 1: "Les pommes que j\'ai (acheté/achetées)"',
      '→ Achetées (COD "que" = pommes, placé avant)',
      '',
      'Exemple 2: "Il (a/à) besoin d\'aide"',
      '→ a (verbe avoir: "Il avait besoin")',
      '',
      'Exemple 3: "Bien qu\'il (pleuve/pleut)"',
      '→ pleuve (subjonctif après "bien que")',
    ],
  },
  comprehension_textes: {
    title: 'Compréhension de Textes',
    content: [
      '🎯 OBJECTIF: Comprendre et analyser des textes (15 questions en 20 min)',
      '',
      'MÉTHODE DE LECTURE EFFICACE',
      '1. Lire D\'ABORD les questions (30 secondes)',
      '   → Identifier ce qui est demandé',
      '   → Repérer les mots-clés à chercher',
      '2. Lire le texte une première fois (2-3 min)',
      '   → Comprendre le sens général',
      '   → Identifier la thèse principale',
      '   → Repérer la structure (intro, développement, conclusion)',
      '3. Relire en cherchant les réponses (5-7 min)',
      '   → Surligner les passages pertinents',
      '   → Noter les arguments et exemples',
      '4. Répondre aux questions (8-10 min)',
      '',
      'IDENTIFIER L\'IDÉE PRINCIPALE',
      '• Chercher dans l\'introduction (1er paragraphe)',
      '• Chercher dans la conclusion (dernier paragraphe)',
      '• Identifier la thèse centrale de l\'auteur',
      '• Éviter les détails secondaires',
      '• L\'idée principale = ce que l\'auteur veut prouver/démontrer',
      '',
      'MOTS-CLÉS ET RELATIONS LOGIQUES',
      '• Mots de cause: "car", "parce que", "en effet", "puisque"',
      '• Mots de conséquence: "donc", "ainsi", "par conséquent", "de ce fait"',
      '• Mots d\'opposition: "mais", "cependant", "néanmoins", "pourtant"',
      '• Mots d\'addition: "de plus", "en outre", "également"',
      '• Mots de but: "pour", "afin de", "dans le but de"',
      '',
      'TYPES DE QUESTIONS',
      '• Idée principale: Chercher la thèse de l\'auteur',
      '  → Souvent dans l\'intro ou la conclusion',
      '• Détails: Repérer les informations précises dans le texte',
      '  → Attention aux dates, chiffres, noms propres',
      '• Inférence: Déduire ce qui n\'est pas explicitement dit',
      '  → Mais basé sur le texte (ne pas inventer)',
      '  → Exemple: Si texte dit "il pleuvait" → on infère "sol mouillé"',
      '• Vocabulaire: Comprendre le sens en contexte',
      '  → Chercher les synonymes/antonymes dans le texte',
      '• Ton de l\'auteur: Analyser les adjectifs, verbes, figures de style',
      '  → Critique: "prétend", "affirme sans preuve"',
      '  → Neutre: faits objectifs',
      '  → Élogieux: "remarquable", "exceptionnel"',
      '',
      'STRUCTURE D\'UN TEXTE ARGUMENTATIF',
      '• Introduction: Présente la thèse',
      '• Développement: Arguments pour/contre',
      '• Conclusion: Synthèse et ouverture',
      '',
      'STRATÉGIES GAGNANTES',
      '• Lire d\'abord les questions pour orienter la lecture',
      '• Surligner les passages importants (si autorisé)',
      '• Attention aux mots de liaison (mais, cependant, donc)',
      '• Distinguer l\'opinion de l\'auteur des faits',
      '• Identifier les synonymes et antonymes',
      '• Repérer les contradictions dans le texte',
      '• Ne pas lire mot à mot, mais par idées',
      '',
      'PIÈGES À ÉVITER',
      '• Ne pas confondre l\'opinion de l\'auteur avec la vôtre',
      '• Éviter les interprétations trop personnelles',
      '• Vérifier que la réponse est bien dans le texte',
      '• Ne pas inventer des informations',
      '• Attention aux questions pièges avec "tous", "aucun", "jamais"',
      '• Ne pas se fier uniquement à la première impression',
      '',
      'ASTUCES GAGNANTES POUR AVOIR DE BONNES NOTES',
      '• LISEZ D\'ABORD LES QUESTIONS (30 sec) - ça change tout !',
      '• Surlignez les mots-clés dans le texte (si autorisé)',
      '• L\'idée principale = souvent dans l\'intro OU la conclusion',
      '• Attention aux mots de liaison: "mais", "cependant", "donc"',
      '• Distinguez l\'opinion de l\'auteur des faits',
      '• Pour les inférences: basé sur le texte, PAS inventé',
      '• Le ton = analyser les adjectifs et verbes utilisés',
      '• Ne confondez pas votre opinion avec celle de l\'auteur',
      '',
      'EXEMPLES DE TEST - QUESTIONS TYPES',
      'Q1: "Quelle est l\'idée principale du texte ?"',
      '  → Chercher dans l\'intro (1er paragraphe) ou conclusion (dernier)',
      '  → Éviter les détails secondaires',
      '  → Réponse: La thèse centrale de l\'auteur',
      '',
      'Q2: "On peut déduire du texte que..."',
      '  → Inférence: basé sur le texte, pas inventé',
      '  → Exemple: Si texte dit "il pleuvait" → on infère "sol mouillé"',
      '  → Réponse: Conclusion logique déduite du texte',
      '',
      'Q3: "Le mot \'remarquable\' dans le contexte signifie..."',
      '  → Chercher le contexte, synonymes/antonymes dans le texte',
      '  → Analyser comment le mot est utilisé',
      '  → Réponse: Sens en contexte (souvent positif)',
      '',
      'Q4: "L\'auteur a un ton..."',
      '  → Analyser les adjectifs et verbes utilisés',
      '  → Critique: "prétend", "affirme sans preuve"',
      '  → Neutre: faits objectifs',
      '  → Élogieux: "remarquable", "exceptionnel"',
      '  → Réponse: Selon les mots utilisés',
      '',
      'Q5: "Le texte mentionne que X, cependant Y. Que peut-on conclure ?"',
      '  → "Cependant" = opposition',
      '  → X et Y sont contradictoires',
      '  → Réponse: Opposition entre X et Y',
      '',
      'Q6: "Selon le texte, quelle affirmation est vraie ?"',
      '  → Vérifier chaque affirmation dans le texte',
      '  → Attention aux mots "tous", "aucun", "jamais"',
      '  → Réponse: Celle qui est explicitement dans le texte',
    ],
    examples: [
      'Exemple 1: Texte parle de "l\'importance de l\'éducation"',
      '→ Idée principale: L\'éducation est essentielle (pas les détails)',
      '',
      'Exemple 2: "L\'auteur utilise le terme \'remarquable\'"',
      '→ Ton élogieux/positif',
      '',
      'Exemple 3: "Le texte mentionne que X, cependant Y"',
      '→ Opposition: X et Y sont contradictoires',
    ],
  },
  conditions_minimales: {
    title: 'Conditions Minimales',
    content: [
      '🎯 OBJECTIF: Identifier les conditions minimales nécessaires (15 questions en 20 min)',
      '',
      'DÉFINITIONS FONDAMENTALES',
      '• Condition NÉCESSAIRE: Sans elle, le résultat est IMPOSSIBLE',
      '  → Exemple: "Avoir 18 ans" est nécessaire pour voter',
      '  → Sans 18 ans, impossible de voter',
      '  → Mais avoir 18 ans ne garantit pas qu\'on vote',
      '• Condition SUFFISANTE: Avec elle, le résultat est GARANTI',
      '  → Exemple: "Être président" est suffisant pour avoir le pouvoir',
      '  → Si on est président, on a le pouvoir',
      '  → Mais d\'autres conditions peuvent aussi suffire',
      '• Condition NÉCESSAIRE ET SUFFISANTE: Équivalence (si et seulement si)',
      '  → Exemple: "Être triangle équilatéral" ↔ "avoir 3 côtés égaux"',
      '',
      'MÉTHODE DE RÉSOLUTION - TABLEAU SYSTÉMATIQUE',
      'Étape 1: Lister TOUTES les conditions données',
      'Étape 2: Créer un tableau de test',
      '',
      'Tableau de test des conditions:',
      '  Condition |  Avec  |  Sans  |  Résultat  |  Nécessaire ?',
      '     A      |   ✓    |   ✗    |  Impossible |     OUI',
      '     B      |   ✓    |   ✓    |  Possible   |     NON',
      '     C      |   ✓    |   ✗    |  Impossible |     OUI',
      '',
      'Étape 3: Identifier les dépendances',
      '  → Si A implique B, alors B est redondant si A est présent',
      '  → Tableau des implications:',
      '        |  A  |  B  |  C',
      '    A   |  -  |  →  |  -',
      '    B   |  -  |  -  |  →',
      '    C   |  -  |  -  |  -',
      '',
      'Étape 4: Tester en retirant chaque condition',
      '  → Si le résultat reste possible, la condition n\'est pas nécessaire',
      '  → Si le résultat devient impossible, la condition est nécessaire',
      '',
      'Étape 5: Garder seulement celles qui sont INDISPENSABLES',
      '',
      'LOGIQUE DES EXPRESSIONS',
      '• "A seulement si B" = B est nécessaire pour A',
      '  → Équivalent à "si A alors B"',
      '  → Exemple: "Tu réussis seulement si tu travailles" = si tu réussis alors tu travailles',
      '• "A si et seulement si B" = A et B sont équivalents',
      '  → A est nécessaire ET suffisant pour B',
      '  → Exemple: "X est pair si et seulement si X est divisible par 2"',
      '• "Tous... sauf" = Tous les X sont Y, sauf Z',
      '  → Exemple: "Tous les jours sauf dimanche" = lundi à samedi',
      '• "Au moins N" = N ou plus (minimum inclus)',
      '  → "Au moins 3" = 3, 4, 5, 6...',
      '• "Au plus N" = N ou moins (maximum inclus)',
      '  → "Au plus 5" = 0, 1, 2, 3, 4, 5',
      '',
      'STRATÉGIES GAGNANTES',
      '• Utiliser des tableaux de vérité',
      '• Tester des cas limites',
      '• Vérifier les implications logiques',
      '• Identifier les conditions redondantes',
      '• Chercher les conditions qui en impliquent d\'autres',
      '',
      'PIÈGES CLASSIQUES',
      '• Ne pas confondre nécessaire et suffisant',
      '  → Si A suffit pour B, on NE PEUT PAS dire que A est nécessaire',
      '  → Plusieurs conditions peuvent suffire',
      '• Attention aux conditions implicites',
      '  → Lire entre les lignes',
      '• Ne pas oublier les conditions évidentes',
      '  → Parfois la condition minimale inclut l\'évidence',
      '',
      'ASTUCES GAGNANTES POUR AVOIR DE BONNES NOTES',
      '• Testez en RETIRANT chaque condition pour voir si elle est nécessaire',
      '• "Nécessaire" = sans elle, impossible',
      '• "Suffisante" = avec elle, garanti',
      '• "Seulement si" = condition nécessaire (A seulement si B = si A alors B)',
      '• "Si et seulement si" = équivalence (nécessaire ET suffisant)',
      '• Utilisez des tableaux de vérité pour les cas complexes',
      '• Attention: plusieurs conditions peuvent être suffisantes',
      '',
      'EXEMPLES DE TEST - QUESTIONS TYPES',
      'Q1: "Pour réussir, il faut: A, B, C. Parmi ces conditions, lesquelles sont minimales ?"',
      '  → Tester en retirant chaque condition',
      '  → Si résultat impossible sans A → A est nécessaire',
      '  → Réponse: Toutes celles qui sont nécessaires',
      '',
      'Q2: "X est nécessaire pour Y" signifie ?',
      '  → Sans X, Y est impossible',
      '  → Mais X ne garantit pas Y',
      '  → Réponse: Sans X, Y est impossible',
      '',
      'Q3: "A seulement si B" signifie ?',
      '  → B est nécessaire pour A',
      '  → Équivalent à "si A alors B"',
      '  → Réponse: Si A alors B (B nécessaire pour A)',
      '',
      'Q4: "Pour voter, il suffit d\'avoir 18 ans"',
      '  → Avoir 18 ans est suffisant (garantit le vote)',
      '  → Mais peut-être pas nécessaire (si d\'autres conditions existent)',
      '  → Réponse: Avoir 18 ans est une condition suffisante',
      '',
      'Q5: "Tous les X sont Y, sauf Z"',
      '  → Tous les X sauf Z sont Y',
      '  → Z est l\'exception',
      '  → Réponse: Tous les X sauf Z sont Y',
      '',
      'Q6: "Au moins 3 conditions parmi A, B, C, D sont nécessaires"',
      '  → Il faut au minimum 3 conditions',
      '  → Mais peut-être plus',
      '  → Réponse: Minimum 3 conditions requises',
    ],
    examples: [
      'Exemple 1: "Pour être admis, il faut: avoir 18 ans, avoir le bac, être français"',
      '→ Si on retire "avoir 18 ans", admission impossible → nécessaire',
      '→ Si on retire "avoir le bac", admission impossible → nécessaire',
      '→ Si on retire "être français", admission impossible → nécessaire',
      '→ Toutes sont minimales',
      '',
      'Exemple 2: "Pour voter, il suffit d\'avoir 18 ans"',
      '→ Avoir 18 ans est suffisant (mais pas nécessaire si d\'autres conditions existent)',
      '',
      'Exemple 3: "Tous les X sont Y, sauf Z"',
      '→ Tous les X sauf Z sont Y',
    ],
  },
  resolution_problemes: {
    title: 'Résolution de Problèmes',
    content: [
      '🎯 OBJECTIF: Résoudre des problèmes mathématiques (15 questions en 20 min)',
      '',
      'MÉTHODE GÉNÉRALE - ÉTAPES ESSENTIELLES',
      '1. Lire attentivement l\'énoncé (2 fois si nécessaire)',
      '   → Surligner les informations importantes',
      '   → Identifier ce qui est demandé',
      '2. Identifier les données et l\'inconnue',
      '   → Lister toutes les données numériques',
      '   → Définir clairement ce qu\'on cherche',
      '3. Choisir la méthode de résolution',
      '   → Équation, proportion, formule, etc.',
      '4. Mettre en équation si nécessaire',
      '   → Traduire le texte en langage mathématique',
      '   → "Le double de X" = 2X',
      '   → "X de plus que Y" = X = Y + ...',
      '   → "X fois plus que Y" = X = Y × ...',
      '5. Résoudre et VÉRIFIER',
      '   → Replacer dans l\'énoncé',
      '   → Vérifier la cohérence',
      '',
      'TABLEAUX DE PROPORTIONNALITÉ - MÉTHODE SYSTÉMATIQUE',
      'Pour résoudre les problèmes de proportion:',
      '',
      'Méthode 1: Produit en croix',
      '  Si A/B = C/D alors A×D = B×C',
      '  Tableau:',
      '     A  |  B',
      '     C  |  D',
      '  → A×D = B×C',
      '',
      'Méthode 2: Coefficient de proportionnalité',
      '  Tableau:',
      '  Donnée  |  Résultat',
      '    3     |     6',
      '    5     |     ?',
      '  → Coefficient k = 6/3 = 2',
      '  → Résultat = 5 × 2 = 10',
      '',
      'TABLEAUX DE PARTAGE - MÉTHODE EN 3 ÉTAPES',
      'Pour partager proportionnellement:',
      '',
      'Étape 1: Calculer le total des parts',
      '  Exemple: Partager selon 2:3:5',
      '  → Total = 2 + 3 + 5 = 10',
      '',
      'Étape 2: Calculer chaque part',
      '  Tableau:',
      '  Personne |  Part  |  Calcul        |  Montant',
      '    1      |   2    |  (2/10) × 100  |   20€',
      '    2      |   3    |  (3/10) × 100  |   30€',
      '    3      |   5    |  (5/10) × 100  |   50€',
      '',
      'Étape 3: Vérifier (somme = montant total)',
      '  → 20€ + 30€ + 50€ = 100€ ✓',
      '',
      'POURCENTAGES - FORMULES ESSENTIELLES',
      '• Calculer x% d\'un nombre: nombre × (x/100)',
      '  → Exemple: 20% de 150 = 150 × 0.20 = 30',
      '• Calculer un pourcentage: (Partie / Total) × 100',
      '  → Exemple: 30 sur 150 = (30/150) × 100 = 20%',
      '• Augmentation de x%: Valeur × (1 + x/100)',
      '  → Exemple: 100€ + 20% = 100 × 1.20 = 120€',
      '• Diminution de x%: Valeur × (1 - x/100)',
      '  → Exemple: 100€ - 15% = 100 × 0.85 = 85€',
      '• PIÈGE: 100€ + 20% puis -20% ≠ 100€',
      '  → 100€ + 20% = 120€',
      '  → 120€ - 20% = 96€ (pas 100€)',
      '  → Les pourcentages ne s\'annulent pas car la base change',
      '• Pourcentage d\'augmentation: ((Final - Initial) / Initial) × 100',
      '  → Exemple: De 100 à 120 = ((120-100)/100) × 100 = 20%',
      '',
      'PROPORTIONNALITÉ',
      '• Produit en croix: Si A/B = C/D alors A×D = B×C',
      '  → Exemple: 2/5 = x/10 → 2×10 = 5×x → x = 4',
      '• Coefficient de proportionnalité: k = résultat / donnée',
      '  → Exemple: Si 3 coûte 6€, alors k = 6/3 = 2',
      '',
      'VITESSE, DISTANCE, TEMPS',
      '• Vitesse = Distance / Temps → V = D / T',
      '• Distance = Vitesse × Temps → D = V × T',
      '• Temps = Distance / Vitesse → T = D / V',
      '• Vitesse moyenne: Distance totale / Temps total',
      '  → Attention: Pas la moyenne des vitesses !',
      '',
      'MOYENNE',
      '• Moyenne = (Somme des valeurs) / (Nombre de valeurs)',
      '  → Exemple: Moyenne de 10, 15, 20 = (10+15+20)/3 = 15',
      '',
      'PARTAGE PROPORTIONNEL',
      '• Calculer le total des parts',
      '• Chaque part = (sa valeur / total) × montant total',
      '  → Exemple: Partager 100€ selon 2:3:5',
      '  → Total parts = 2+3+5 = 10',
      '  → Premier: (2/10) × 100 = 20€',
      '  → Deuxième: (3/10) × 100 = 30€',
      '  → Troisième: (5/10) × 100 = 50€',
      '',
      'TYPES DE PROBLÈMES FRÉQUENTS',
      '• Proportions et pourcentages',
      '• Problèmes de vitesse, distance, temps',
      '• Problèmes de partage',
      '• Problèmes de mélange',
      '• Problèmes d\'âge',
      '• Problèmes de travail (taux de travail)',
      '',
      'STRATÉGIES GAGNANTES',
      '• Faire un schéma si utile (dessiner la situation)',
      '• Traduire en équations',
      '• Utiliser des valeurs numériques simples pour tester',
      '• Vérifier la cohérence du résultat',
      '• Vérifier les unités',
      '• Ne pas hésiter à tester les réponses proposées',
      '',
      'PIÈGES CLASSIQUES',
      '• Attention aux unités (km/h, m/s, etc.)',
      '• Vérifier que la réponse répond bien à la question',
      '• Ne pas oublier les cas particuliers',
      '• Les pourcentages successifs ne s\'annulent pas',
      '• Vitesse moyenne ≠ moyenne des vitesses',
      '',
      'ASTUCES GAGNANTES POUR AVOIR DE BONNES NOTES',
      '• LISEZ 2 FOIS l\'énoncé avant de commencer',
      '• Surlignez les données numériques',
      '• Identifiez clairement ce qui est demandé',
      '• Vérifiez TOUJOURS votre réponse en la replaçant dans l\'énoncé',
      '• Attention aux unités (km/h, m/s, €, etc.)',
      '• Les pourcentages successifs NE S\'ANNULENT PAS',
      '• Vitesse moyenne ≠ moyenne des vitesses',
      '• Testez avec des valeurs simples si vous êtes bloqué',
      '',
      'EXEMPLES DE TEST - QUESTIONS TYPES',
      'Q1: "Un prix passe de 80€ à 100€. Quelle est l\'augmentation en % ?"',
      '  → ((100-80)/80) × 100 = (20/80) × 100 = 0.25 × 100 = 25%',
      '  → Réponse: 25%',
      '',
      'Q2: "Partager 120€ selon 1:2:3"',
      '  → Total parts = 1+2+3 = 6',
      '  → 1ère: (1/6) × 120 = 20€',
      '  → 2ème: (2/6) × 120 = 40€',
      '  → 3ème: (3/6) × 120 = 60€',
      '  → Réponse: 20€, 40€, 60€',
      '',
      'Q3: "Un train fait 240 km en 2h. Quelle est sa vitesse ?"',
      '  → V = D/T = 240/2 = 120 km/h',
      '  → Réponse: 120 km/h',
      '',
      'Q4: "Si un prix augmente de 10% puis baisse de 10%, retrouve-t-on le prix initial ?"',
      '  → 100€ + 10% = 110€',
      '  → 110€ - 10% = 99€ (pas 100€)',
      '  → NON, les pourcentages ne s\'annulent pas',
      '  → Réponse: Non',
      '',
      'Q5: "Un cycliste fait 60 km en 2h, puis 40 km en 1h. Vitesse moyenne ?"',
      '  → Distance totale = 60 + 40 = 100 km',
      '  → Temps total = 2 + 1 = 3h',
      '  → Vitesse moyenne = 100/3 ≈ 33.3 km/h',
      '  → ATTENTION: Pas (30+40)/2 = 35 km/h !',
      '  → Réponse: 33.3 km/h',
      '',
      'Q6: "Un article coûte 80€. Il augmente de 25%. Quel est le nouveau prix ?"',
      '  → 80 × (1 + 25/100) = 80 × 1.25 = 100€',
      '  → Réponse: 100€',
      '',
      'Q7: "15% de 240 = ?"',
      '  → 10% = 24, 5% = 12',
      '  → 15% = 24 + 12 = 36',
      '  → Réponse: 36',
      '',
      'Q8: "Un prix baisse de 20%. De quel % doit-il remonter pour revenir au prix initial ?"',
      '  → 100€ - 20% = 80€',
      '  → Pour revenir à 100€: ((100-80)/80) × 100 = 25%',
      '  → Il doit remonter de 25% (pas 20%)',
      '  → Réponse: 25%',
    ],
    examples: [
      'Exemple 1: "Un article coûte 80€. Il augmente de 25%. Quel est le nouveau prix ?"',
      '→ 80 × 1.25 = 100€',
      '',
      'Exemple 2: "Un cycliste fait 60 km en 2h, puis 40 km en 1h. Vitesse moyenne ?"',
      '→ Distance totale = 100 km, Temps total = 3h',
      '→ Vitesse moyenne = 100/3 ≈ 33.3 km/h (pas la moyenne de 30 et 40)',
      '',
      'Exemple 3: "Partager 150€ entre 3 personnes selon 2:3:4"',
      '→ Total parts = 9',
      '→ 1ère: (2/9) × 150 = 33.33€',
      '→ 2ème: (3/9) × 150 = 50€',
      '→ 3ème: (4/9) × 150 = 66.67€',
    ],
  },
};

export default function CheatsheetPage() {
  const params = useParams();
  const router = useRouter();
  const sectionParam = params.section as string | undefined;
  const section: SectionId = (SECTION_IDS.includes(sectionParam as SectionId) 
    ? sectionParam 
    : SECTION_IDS[0]) as SectionId;
  
  const sectionData = SECTIONS[section];
  const cheatsheet = CHEATSHEETS[section] || CHEATSHEETS.calcul_mental;

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      <Navbar />
      <div className="container mx-auto px-4 py-8">
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold mb-2">Cheat Sheet - {sectionData.name}</h1>
            <p className="text-gray-600 dark:text-gray-400">
              Résumé des méthodes et formules essentielles
            </p>
          </div>
          <div className="flex items-center space-x-4">
            <Select
              value={section}
              onChange={(e) => router.push(`/cheatsheet/${e.target.value}`)}
              className="w-auto"
            >
              {SECTION_IDS.map((sectionId) => (
                <option key={sectionId} value={sectionId}>
                  {SECTIONS[sectionId].name}
                </option>
              ))}
            </Select>
            <Button onClick={handlePrint} variant="outline">
              <Printer className="h-4 w-4 mr-2" />
              Imprimer
            </Button>
          </div>
        </div>

        <Card className="print:shadow-none print:border-0">
          <CardHeader>
            <CardTitle className="text-2xl">{cheatsheet.title}</CardTitle>
            <CardDescription>Méthodes, formules et astuces essentielles</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="prose dark:prose-invert max-w-none">
              <div className="space-y-2 font-mono text-sm">
                {cheatsheet.content.map((line, idx) => {
                  if (line === '') {
                    return <div key={idx} className="h-2" />;
                  }
                  if (line.startsWith('•')) {
                    return (
                      <div key={idx} className="ml-4 text-gray-700 dark:text-gray-300">
                        {line}
                      </div>
                    );
                  }
                  if (line.startsWith('  →')) {
                    return (
                      <div key={idx} className="ml-8 text-gray-600 dark:text-gray-400 text-xs italic">
                        {line}
                      </div>
                    );
                  }
                  if (line.startsWith('Q:')) {
                    return (
                      <div key={idx} className="ml-4 mt-3 text-blue-700 dark:text-blue-400 font-semibold">
                        {line}
                      </div>
                    );
                  }
                  return (
                    <div
                      key={idx}
                      className="font-bold text-lg mt-4 mb-2 text-gray-900 dark:text-gray-100"
                    >
                      {line}
                    </div>
                  );
                })}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Exemples concrets */}
        {cheatsheet.examples && cheatsheet.examples.length > 0 && (
          <Card className="mt-6 border-blue-200 dark:border-blue-800">
            <CardHeader>
              <CardTitle className="text-xl text-blue-700 dark:text-blue-400">
                📝 Exemples Concrets de Test
              </CardTitle>
              <CardDescription>Questions types que vous pourriez rencontrer</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {cheatsheet.examples.map((example, idx) => {
                  if (example === '') {
                    return <div key={idx} className="h-2" />;
                  }
                  if (example.startsWith('Exemple')) {
                    return (
                      <div key={idx} className="font-semibold text-base text-gray-900 dark:text-gray-100 mt-2">
                        {example}
                      </div>
                    );
                  }
                  if (example.startsWith('→')) {
                    return (
                      <div key={idx} className="ml-4 text-gray-700 dark:text-gray-300 bg-gray-50 dark:bg-gray-800/50 p-2 rounded">
                        {example}
                      </div>
                    );
                  }
                  return (
                    <div key={idx} className="text-sm text-gray-600 dark:text-gray-400">
                      {example}
                    </div>
                  );
                })}
              </div>
            </CardContent>
          </Card>
        )}

        {/* Additional Tips */}
        <Card className="mt-6">
          <CardHeader>
            <CardTitle>💡 Conseils Généraux pour Réussir</CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2 text-sm">
              <li>• <strong>Entraînez-vous régulièrement</strong> pour automatiser les méthodes</li>
              <li>• <strong>Mémorisez les formules</strong> les plus fréquentes (carrés, pourcentages, etc.)</li>
              <li>• <strong>Gérez votre temps</strong>: 20 min pour 15 questions = ~1min20 par question</li>
              <li>• <strong>Ne bloquez pas</strong>: Passez à la suivante si vous êtes coincé</li>
              <li>• <strong>Vérifiez vos réponses</strong> si le temps le permet</li>
              <li>• <strong>Restez calme</strong> et méthodique</li>
              <li>• <strong>Lisez attentivement</strong> les énoncés (souvent les erreurs viennent de là)</li>
            </ul>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

